#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTicketer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITicket")]
	public partial class LookupClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTicket(Ticket instance);
    partial void UpdateTicket(Ticket instance);
    partial void DeleteTicket(Ticket instance);
    #endregion
		
		public LookupClassesDataContext() : 
				base(global::SampleTicketer.Properties.Settings.Default.ITicketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LookupClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ticket> Tickets
		{
			get
			{
				return this.GetTable<Ticket>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ticket")]
	public partial class Ticket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ticketNum;
		
		private string _fname;
		
		private string _lname;
		
		private string _email;
		
		private string _phoneNumber;
		
		private System.DateTime _dateCreated;
		
		private System.Nullable<System.DateTime> _dateDue;
		
		private string _assignedPriority;
		
		private string _personOriginallyAssigned;
		
		private string _personAssigned;
		
		private string _descriptionInput;
		
		private string _statusType;
		
		private System.Nullable<int> _timeSpentWorking;
		
		private string _userName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnticketNumChanging(int value);
    partial void OnticketNumChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OndateCreatedChanging(System.DateTime value);
    partial void OndateCreatedChanged();
    partial void OndateDueChanging(System.Nullable<System.DateTime> value);
    partial void OndateDueChanged();
    partial void OnassignedPriorityChanging(string value);
    partial void OnassignedPriorityChanged();
    partial void OnpersonOriginallyAssignedChanging(string value);
    partial void OnpersonOriginallyAssignedChanged();
    partial void OnpersonAssignedChanging(string value);
    partial void OnpersonAssignedChanged();
    partial void OndescriptionInputChanging(string value);
    partial void OndescriptionInputChanged();
    partial void OnstatusTypeChanging(string value);
    partial void OnstatusTypeChanged();
    partial void OntimeSpentWorkingChanging(System.Nullable<int> value);
    partial void OntimeSpentWorkingChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    #endregion
		
		public Ticket()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticketNum", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ticketNum
		{
			get
			{
				return this._ticketNum;
			}
			set
			{
				if ((this._ticketNum != value))
				{
					this.OnticketNumChanging(value);
					this.SendPropertyChanging();
					this._ticketNum = value;
					this.SendPropertyChanged("ticketNum");
					this.OnticketNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(20)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(20)")]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateCreated", DbType="Date NOT NULL")]
		public System.DateTime dateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if ((this._dateCreated != value))
				{
					this.OndateCreatedChanging(value);
					this.SendPropertyChanging();
					this._dateCreated = value;
					this.SendPropertyChanged("dateCreated");
					this.OndateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateDue", DbType="Date")]
		public System.Nullable<System.DateTime> dateDue
		{
			get
			{
				return this._dateDue;
			}
			set
			{
				if ((this._dateDue != value))
				{
					this.OndateDueChanging(value);
					this.SendPropertyChanging();
					this._dateDue = value;
					this.SendPropertyChanged("dateDue");
					this.OndateDueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedPriority", DbType="VarChar(30)")]
		public string assignedPriority
		{
			get
			{
				return this._assignedPriority;
			}
			set
			{
				if ((this._assignedPriority != value))
				{
					this.OnassignedPriorityChanging(value);
					this.SendPropertyChanging();
					this._assignedPriority = value;
					this.SendPropertyChanged("assignedPriority");
					this.OnassignedPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personOriginallyAssigned", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string personOriginallyAssigned
		{
			get
			{
				return this._personOriginallyAssigned;
			}
			set
			{
				if ((this._personOriginallyAssigned != value))
				{
					this.OnpersonOriginallyAssignedChanging(value);
					this.SendPropertyChanging();
					this._personOriginallyAssigned = value;
					this.SendPropertyChanged("personOriginallyAssigned");
					this.OnpersonOriginallyAssignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personAssigned", DbType="VarChar(30)")]
		public string personAssigned
		{
			get
			{
				return this._personAssigned;
			}
			set
			{
				if ((this._personAssigned != value))
				{
					this.OnpersonAssignedChanging(value);
					this.SendPropertyChanging();
					this._personAssigned = value;
					this.SendPropertyChanged("personAssigned");
					this.OnpersonAssignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionInput", DbType="VarChar(1500) NOT NULL", CanBeNull=false)]
		public string descriptionInput
		{
			get
			{
				return this._descriptionInput;
			}
			set
			{
				if ((this._descriptionInput != value))
				{
					this.OndescriptionInputChanging(value);
					this.SendPropertyChanging();
					this._descriptionInput = value;
					this.SendPropertyChanged("descriptionInput");
					this.OndescriptionInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusType", DbType="VarChar(20)")]
		public string statusType
		{
			get
			{
				return this._statusType;
			}
			set
			{
				if ((this._statusType != value))
				{
					this.OnstatusTypeChanging(value);
					this.SendPropertyChanging();
					this._statusType = value;
					this.SendPropertyChanged("statusType");
					this.OnstatusTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeSpentWorking", DbType="Int")]
		public System.Nullable<int> timeSpentWorking
		{
			get
			{
				return this._timeSpentWorking;
			}
			set
			{
				if ((this._timeSpentWorking != value))
				{
					this.OntimeSpentWorkingChanging(value);
					this.SendPropertyChanging();
					this._timeSpentWorking = value;
					this.SendPropertyChanged("timeSpentWorking");
					this.OntimeSpentWorkingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(30)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
